
#deploy a sample web server in the sandbox namespace with label user
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web-a123456
  namespace: default
  labels:
    user: a123456
spec:
  replicas: 2
  selector:
    matchLabels:
      user: a123456
  template:
    metadata:
      labels:
        user: a123456
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
